# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Builds all the solution projects and all of its dependencies
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore

      - name: Publish app and its dependencies to a folder for deployment
        run: dotnet publish ConselvaBudget/ConselvaBudget.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-restore

      - name: Install Entity Framework Core tool
        run: dotnet tool install -g dotnet-ef

      - name: Create migration bundle for ConselvaBudgetContext
        run: dotnet ef migrations bundle --runtime linux-x64 -p ConselvaBudget/ConselvaBudget.csproj -c ConselvaBudgetContext -o ${{env.DOTNET_ROOT}}/myapp/migrate-conselvabudget

      - name: Create migration bundle for ApplicationDbContext
        run: dotnet ef migrations bundle --runtime linux-x64 -p ConselvaBudget/ConselvaBudget.csproj -c ApplicationDbContext -o ${{env.DOTNET_ROOT}}/myapp/migrate-applicationdb

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_019B29CE7DA84250B76E917876C06891 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_720161AC6B504C63AEDE91748A93011F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_96BF054F210845A8A8DA5A066699BEE8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'conselva-staging-a'
          slot-name: 'Production'
          package: .
          