# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - conselvanet

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build all the solution projects
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore

      - name: Publish app and its dependencies to a folder for deployment
        run: dotnet publish ConselvaBudget/ConselvaBudget.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-restore

      - name: Install Entity Framework Core tool
        run: dotnet tool install -g dotnet-ef

      - name: Create migration bundle for ConselvaBudgetContext
        run: dotnet ef migrations bundle --runtime linux-x64 -p ConselvaBudget/ConselvaBudget.csproj -c ConselvaBudgetContext -o ${{env.DOTNET_ROOT}}/myapp/migrate-conselvabudget

      - name: Create migration bundle for AppIdentityContext
        run: dotnet ef migrations bundle --runtime linux-x64 -p ConselvaBudget/ConselvaBudget.csproj -c AppIdentityContext -o ${{env.DOTNET_ROOT}}/myapp/migrate-appidentity

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF91C3FD2F31437099F127BD856E7ABD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0851E9C2200841A2B524A50A43FA9FEA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16DCB34280EE44B3AD5458646A8BE18E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'conselvanet'
          slot-name: 'staging'
          package: .
          